name: Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

        # Checkout the code
      - uses: actions/checkout@v3

        # Install proper version of node
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

        # Install v3.7.1 of gatsby-cli
      - run: npm install -g gatsby-cli@3.7.1

        # Install project dependencies
      - run: npm install

        # Run gatsby build
      - run: gatsby build
        env: 
          MAP_GOOGLE_API_KEY: ${{ secrets.MAP_GOOGLE_API_KEY }}

      # check env variable
      - run: echo $MAP_GOOGLE_API_KEY
        env: 
          MAP_GOOGLE_API_KEY: ${{ secrets.MAP_GOOGLE_API_KEY }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
            publish-dir: './public'
            production-branch: master
            deploy-message: "Deploy from GitHub Actions"
        env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 20